name: wpfui-pr-deploy

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: microsoft/setup-msbuild@v1.3
              with:
                  msbuild-architecture: x64
            - uses: nuget/setup-nuget@v1
              with:
                  nuget-api-key: ${{ secrets.NUGET_API_KEY }}

            - name: Restore dependencies
              run: nuget restore Wpf.Ui.sln

            - name: Build the solution
              run: msbuild src\Wpf.Ui\Wpf.Ui.csproj -p:Configuration=Release -p:Platform="Any CPU" -p:GITHUB_ACTIONS=True -p:ContinuousIntegrationBuild=true -m -graph -isolate

            - name: Publish the package to NuGet.org
              run: nuget push **\*.nupkg -NonInteractive -SkipDuplicate -Source 'https://api.nuget.org/v3/index.json'

            - name: Publish the symbols to NuGet.org
              run: nuget push **\*.snupkg -NonInteractive -SkipDuplicate -Source 'https://api.nuget.org/v3/index.json'
